GitAspx/ViewModels/DirectoryListViewModel.cs
#region License

// Copyright 2010 Jeremy Skinner (http://www.jeremyskinner.co.uk)
//  
// Licensed under the Apache License, Version 2.0 (the "License"); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
// 
// http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
// 
// The latest version of this file can be found at http://github.com/JeremySkinner/git-dot-aspx

#endregion

namespace GitAspx.ViewModels {
	using System.Collections.Generic;
	using System.IO;
	using GitAspx.Lib;

	public class DirectoryListViewModel {
		public string RepositoriesDirectory { get; set; }
		public List<RepositoryViewModel> Repositories { get; set; }
	}
}

GitAspx/Controllers/DirectoryListController.cs
#region License

// Copyright 2010 Jeremy Skinner (http://www.jeremyskinner.co.uk)
//  
// Licensed under the Apache License, Version 2.0 (the "License"); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
// 
// http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
// 
// The latest version of this file can be found at http://github.com/JeremySkinner/git-dot-aspx

#endregion

namespace GitAspx.Controllers
{
    using System.Web.Mvc;
    using GitAspx.Lib;
    using GitAspx.ViewModels;
    using System.Linq;
    using System.Web;
    using System.Web.Security;
    using System.Security.Principal;

    public class DirectoryListController : Controller
    {
        readonly RepositoryService repositories;

        public DirectoryListController(RepositoryService repositories)
        {
            this.repositories = repositories;
        }

        [FormAuthorizeEventually(IsEventual = true)]
        public ActionResult Index()
        {
            var dlvm = new DirectoryListViewModel
            {
                RepositoriesDirectory = repositories.GetRepositoriesDirectory().FullName,
                Repositories = repositories.GetAllRepositories().Select(x => new RepositoryViewModel(x)).ToList()
            };

            bool isAuthenticated = HttpContext.User.Identity.IsAuthenticated;
            for (int i = dlvm.Repositories.Count() - 1; i >= 0; i--)
            {
                bool canRead = false;
                if (isAuthenticated)
                {
                    canRead = AuthService.CanRead(dlvm.Repositories[i].Name, HttpContext.User.Identity.Name);
                }
                if (!AuthService.IsRepositoryPublic(dlvm.Repositories[i].Name) && !canRead)
                {
                    dlvm.Repositories.RemoveAt(i);
                }
            }
            return View(dlvm);
        }

        [HttpPost]
        [FormAuthorizeEventually]
        public ActionResult Create(string project)
        {
            if (!AuthService.IsAdmin(HttpContext.User.Identity.Name) || !HttpContext.User.Identity.IsAuthenticated)
            {
                return new HttpUnauthorizedResult();
            }
            if (!string.IsNullOrEmpty(project))
            {
                repositories.CreateRepository(project);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [FormAuthorizeEventually]
        public ActionResult Delete(string project)
        {
            if (!AuthService.IsAdmin(HttpContext.User.Identity.Name) || !HttpContext.User.Identity.IsAuthenticated)
            {
                return new HttpUnauthorizedResult();
            }
            return View();
        }
    }
}

GitAspx/Views/DirectoryList/Index.cshtml
@model GitAspx.ViewModels.DirectoryListViewModel
@using GitAspx;
@{
    ViewBag.Title = "Repositories";
}
<div class="repositoryContainer">
    <h1>
        Repository</h1>
    <a href="javascript:void(0)" class="createRepository">Create a new bare repository</a>
    <div class="clear">
    </div>
    <ul id="repositories">
        @foreach (var repository in Model.Repositories)
        {
            <li><a class="repository" href="javascript:void(0)" title="@Url.ProjectUrl(repository.Name)">
                @repository.Name
                <span class="latest-commit">@repository.LatestCommitInfo  Login:Anonymous Password:Anonymous</span>  </a>
                <ul>
                    <li><a class="browse" href="javascript:void(0)" title="@repository.Name">Browse</a></li>
                    <li><a class="delete" href="javascript:void(0)" title="@repository.Name">Delete</a></li>
                </ul>
            </li>
        }
    </ul>
</div>
<div class="jqmWindow" id="dialog">
    <div class="title">
        Clone the repository using this command <a href="#" class="jqmClose">
            <img src="@Url.Content("~/Content/images/close.png")" alt="Close" /></a></div>
    <div class="content">
        <pre>git clone
<input type="text" id="repository-url" /></pre>
    </div>
</div>
<div class="jqmWindow" id="createRepositoryDialog">
    <div class="title">
        Create a new repository <a href="#" class="jqmClose">
            <img src="@Url.Content("~/Content/images/close.png")" alt="Close" /></a></div>
    <div class="content">
        @using (Html.BeginForm("Create", "DirectoryList"))
        {
            <input type="text" name="project" />@:.git<br />
		<input type="submit" value="Create a new repository" class="button" />
        }
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $('#dialog').jqm();
        $('#createRepositoryDialog').jqm();

        $('#repository-url').click(function () {
            $(this).select();
        });

        $('a.repository').click(function () {
            var url = $(this).attr('title');
            $('#dialog').jqmShow();
            $('#repository-url').val(url).focus().select();
        });

        $('a.browse').click(function () {
            var url = encodeURI($(this).attr('title'));
            document.location.href = '/Browse/Index?project=' + url;

        });

        $('a.delete').click(function () {
            var url = encodeURI($(this).attr('title'));
            document.location.href = '/Delete?project=' + url;
        });

        $('a.createRepository').click(function () {
            $('#createRepositoryDialog').jqmShow();
        });
    });
</script>
</asp:Content> 